rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz3/Krz_02001HM10.txt")
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz3/Krz_02001_Hi0-1000_LS255_In10.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz3/Krz_02001_Hi0-1000_LS80_In10.txt",head=TRUE)
plot(rt2$MinZenith,rt3$GapFraction,type="l")
lines(rt2$MinZenith,rt1$V2,type="l",lty="dashed")
lines(rt2$MinZenith,rt2$GapFraction,type="l",lty="dotted")


rt1<- read.table("D:/Work/Stn3/Stn_03002HM5.txt")
rt2<- read.table("D:/Work/Stn3/Stn_03002_Hi0-1000_LS80_In5.txt",head=TRUE)
rt3<- read.table("D:/Work/Stn3/Stn_03002_Hi24-1000_LS80_In5.txt",head=TRUE)
plot(rt2$MinZenith,rt1$V2,type="l",col="red", ylab="GapFraction",xlab="Zenith",ylim=c(0,1))
lines(rt2$MinZenith,rt3$GapFraction,type="l",lty="dashed",col="green")
lines(rt2$MinZenith,rt2$GapFraction,type="l",lty="dotted",col="blue")


rt1<- read.table("D:/Work/Stn3/Stn_03002_Hi14-16_LS80_In5.txt",head=TRUE)
rt2<- read.table("D:/Work/Stn3/Stn_03002_Hi20-22_LS80_In5.txt",head=TRUE)
rt3<- read.table("D:/Work/Stn3/Stn_03002_Hi24-1000_LS80_In5.txt",head=TRUE)
plot(rt2$MinZenith,rt1$GapFraction,type="l",col="red", ylab="GapFraction",xlab="Zenith",ylim=c(0,1))
lines(rt2$MinZenith,rt3$GapFraction,type="l",lty="dashed",col="green")
lines(rt2$MinZenith,rt2$GapFraction,type="l",lty="dotted",col="blue")

rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_03001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_03003_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_03HM5.TXT",head=TRUE)
plot(rt1$MinZenith,rt1$GapFraction,type="l",col="red", ylab="GapFraction",xlab="Zenith",ylim=c(0,1))
lines(rt1$MinZenith,rt2$GapFraction,type="l",lty="dashed",col="green")
lines(rt1$MinZenith,rt3$GapFraction,type="l",lty="dotted",col="blue")




rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03002_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03002_Hi0-24_LS80_In5_Record.txt",head=TRUE)
plot(rt1$MinZenith,rt1$GapFraction,type="l",col="red", ylab="GapFraction",xlab="Zenith",ylim=c(0,0.4))
lines(rt2$MinZenith,rt2$GapFraction,type="l",lty="dashed",col="green")


rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_03HM5.TXT")
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_03001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_03003_Hi0-35_LS80_In5_Record.txt",head=TRUE)
plot(rt1$V2,rt1$V4,type="l",col="red", ylab="GapFraction",xlab="Zenith",ylim=c(0,0.05))
lines(rt1$V2,rt2$GapFraction,type="l",lty="dashed",col="green")
lines(rt1$V2,rt3$GapFraction,type="l",lty="dotted",col="blue")

rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_02HM5.TXT")
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_02001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_02003_Hi0-35_LS80_In5_Record.txt",head=TRUE)
plot(rt1$V2,rt1$V4,type="l",col="red", ylab="GapFraction",xlab="Zenith",ylim=c(0,0.06))
lines(rt1$V2,rt2$GapFraction,type="l",lty="dashed",col="green")
lines(rt1$V2,rt3$GapFraction,type="l",lty="dotted",col="blue")


rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03HM5.TXT")
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03004_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03004_Hi0-35_LS255_In5_Record.txt",head=TRUE)
plot(rt1$V2,rt1$V4,type="l",col="red", ylab="GapFraction",xlab="Zenith",ylim=c(0,0.06))
lines(rt1$V2,rt2$GapFraction,type="l",lty="dashed",col="green")
lines(rt1$V2,rt3$GapFraction,type="l",lty="dotted",col="blue")


rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_03HM5.TXT")
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_03003_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_03003_Hi0-35_LS255_In5_Record.txt",head=TRUE)
plot(rt1$V2,rt1$V4,type="l",col="red", ylab="GapFraction",xlab="Zenith",ylim=c(0,0.06))
lines(rt1$V2,rt2$GapFraction,type="l",lty="dashed",col="green")
lines(rt1$V2,rt3$GapFraction,type="l",lty="dotted",col="blue")



rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01002_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01002_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01002_Hi0-35_LS120_In5_Record.txt",head=TRUE)
plot(rt1$MinZenith,rt1$GapFraction,type="l",col="red", ylab="GapFraction",xlab="Zenith",ylim=c(0,0.65))
lines(rt1$MinZenith,rt2$GapFraction,type="l",lty="dashed",col="green")
lines(rt1$MinZenith,rt3$GapFraction,type="l",lty="dotted",col="blue")


rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_9bHM5.TXT")
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01002_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01002_Hi0-35_LS255_In5_Record.txt",head=TRUE)
plot(rt1$V2,rt1$V4,type="l",col="red", ylab="GapFraction",xlab="Zenith",ylim=c(0,0.8))
lines(rt1$V2,rt2$GapFraction,type="l",lty="dashed",col="green")
lines(rt1$V2,rt3$GapFraction,type="l",lty="dotted",col="blue")

rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/01005_SB80_0.5In5.txt",head=TRUE)
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/02001_SB80_0.5In5.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/03002_SB80_0.5In5.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$Leafangle,type="l",col="red", ylab="x->G",xlab="Height",ylim=c(0,10))
lines((rt2$down+rt2$up)/2,rt2$Leafangle,type="l",lty="dashed",col="red")
lines((rt3$down+rt3$up)/2,rt3$Leafangle,type="l",lty="dotted",col="red")
axis(4,at=c(0,2,4,6,8,10),labels=c(0,0.2,0.4,0.6,0.8,1), col.axis = "green")
lines((rt1$down+rt1$up)/2,rt2$LAI/(rt1$up-rt1$down)*10,type="l",lty="dashed",col="green")

rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB01001_SB80_0.5In5.txt",head=TRUE)
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB01002_SB80_0.5In5.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down),type="l",col="red", ylab="LAD",xlab="Height",ylim=c(0.4,1))
lines((rt2$down+rt2$up)/2,rt2$LAI/(rt2$up-rt2$down),type="l",lty="dashed",col="green")




rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB01001_SB80_0.5In5.txt",head=TRUE)
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB01002_SB80_0.5In5.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$Leafangle,type="l",col="red", ylab="x->G",xlab="Height",ylim=c(0,3))
lines((rt2$down+rt2$up)/2,rt2$Leafangle,type="l",lty="dashed",col="green")

rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn01005_SB80_0.5In5.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$Leafangle,type="l",col="red", ylab="x->G",xlab="Height",ylim=c(0,6))
lines((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down)*5,type="l",lty="dashed",col="green")


rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn02001_SB80_0.5In5.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$Leafangle,type="l",col="red", ylab="x->G",xlab="Height")
lines((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down)*5,type="l",lty="dashed",col="green")
axis(4,0:10,c(0:10)/5)

rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn03002_SB80_0.5In5.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$Leafangle,type="l",col="red", ylab="x->G",xlab="Height",ylim=c(0,6))
lines((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down)*5,type="l",lty="dashed",col="green")


rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn01005_SB80_0.5In5.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",xlim=c(5,28),ylim=c(0,6),pch=19)
lines((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height")
points((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down)*5,pch=21)
lines((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down)*5)
axis(4,0:6,c(0:6)/5)






rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn03002_SB80_0.5In5.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",xlim=c(5,28),ylim=c(0,6),pch=19)
lines((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height")
points((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down)*5,pch=21)
lines((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down)*5)
axis(4,0:6,c(0:6)/5)

rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn020042_SB80_0.5In5.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",xlim=c(5,28),ylim=c(0,6),pch=19)
lines((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height")
points((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down)*5,pch=21)
lines((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down)*5)
axis(4,0:6,c(0:6)/5)






rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn01005_SB80_0.5In5.txt",head=TRUE)
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn020042_SB80_0.5In5.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn03002_SB80_0.5In5.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",xlim=c(15,27),ylim=c(0,6),pch=19)
lines((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height")
points((rt2$down+rt2$up)/2,rt2$Leafangle,pch=24)
lines((rt2$down+rt2$up)/2,rt2$Leafangle)
points((rt3$down+rt3$up)/2,rt3$Leafangle,pch=21)
lines((rt3$down+rt3$up)/2,rt3$Leafangle,lty="dashed")



rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB01001_SB80_0.5In5.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",xlim=c(4,10),ylim=c(0,3),pch=19)
lines((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height")
points((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down),pch=21)
lines((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down))
axis(4)


rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB0242001_SB80_0.5In5.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",xlim=c(4,12),ylim=c(0,3),pch=19)
lines((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height")
points((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down),pch=21)
lines((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down))
axis(4)

rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB0341001_SB80_0.5In5.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",xlim=c(4,11),ylim=c(0,3),pch=19)
lines((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height")
points((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down),pch=21)
lines((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down))
axis(4)


rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn01005_SB80_0.5In5.txt",head=TRUE)
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn03002_SB80_0.5In5.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_Manual_2.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",xlim=c(14,27),ylim=c(0,6),pch=19)
lines((rt1$down+rt1$up)/2,rt1$Leafangle)
points((rt2$down+rt2$up)/2,rt2$Leafangle,pch=24)
lines((rt2$down+rt2$up)/2,rt2$Leafangle)
points((rt3$down+rt3$up)/2-1,rt3$Leafangle,pch=21)
lines((rt3$down+rt3$up)/2-1,rt3$Leafangle,lty="dashed")


rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01002_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01HM5.TXT")
plot(rt1$MinZenith,rt1$GapFraction, ylab="GapFraction",xlab="Zenith",ylim=c(0,0.1),pch=19)
lines(rt1$MinZenith,rt1$GapFraction,lty="dashed")
points(rt1$MinZenith,rt2$GapFraction,pch=21)
lines(rt1$MinZenith,rt2$GapFraction,lty="dashed")
points(rt1$V2,rt3$V4,pch=24)
lines(rt1$V2,rt3$V4)

rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01002_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi0-35_LS255_In5_Record.txt",head=TRUE)
plot(rt1$MinZenith,rt1$GapFraction, ylab="GapFraction",xlab="Zenith",ylim=c(0,0.1),pch=19)
lines(rt1$MinZenith,rt1$GapFraction,lty="dashed")
points(rt1$MinZenith,rt2$GapFraction,pch=21)
lines(rt1$MinZenith,rt2$GapFraction,lty="dashed")
points(rt1$MinZenith,rt3$GapFraction,pch=24)
lines(rt1$MinZenith,rt3$GapFraction)

rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01HM5.TXT",head=TRUE)
plot(rt1$MinZenith,rt1$GapFraction, ylab="GapFraction",xlab="Zenith",ylim=c(0,0.1),pch=19)
lines(rt1$MinZenith,rt1$GapFraction,lty="dashed")
points(rt1$MinZenith,rt2$GapFraction,pch=21)
lines(rt1$MinZenith,rt2$GapFraction,lty="dashed")
points(rt1$MinZenith,rt3$GapFraction,pch=24)
lines(rt1$MinZenith,rt3$GapFraction)

rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03002_Hi25.5-26_LS80_In5_Record.txt",head=TRUE)
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03002_Hi25.5-26_LS255_In5_Record.txt",head=TRUE)
plot(rt1$MinZenith,rt1$GapFraction, ylab="GapFraction",xlab="Zenith",ylim=c(0,1),pch=19)
lines(rt1$MinZenith,rt1$GapFraction,lty="dashed")
points(rt1$MinZenith,rt2$GapFraction,pch=21)
lines(rt1$MinZenith,rt2$GapFraction,lty="dashed")





rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB01001_SB80_0.5In5.txt",head=TRUE)
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB0242001_SB80_0.5In5.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB0341001_SB80_0.5In5.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",xlim=c(4,10),ylim=c(0,3),pch=19)
lines((rt1$down+rt1$up)/2,rt1$Leafangle)
points((rt2$down+rt2$up)/2,rt2$Leafangle,pch=24)
lines((rt2$down+rt2$up)/2,rt2$Leafangle)
points((rt3$down+rt3$up)/2,rt3$Leafangle,pch=21)
lines((rt3$down+rt3$up)/2,rt3$Leafangle,lty="dashed")



rt11<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_9bHM5.TXT")
rt12<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_3bHM5.TXT")
rt13<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_15bHM5.TXT")
rt21<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt22<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0242001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt23<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0341001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
plot(rt11$V2,rt11$V4, ylab="GapFraction",xlab="Zenith",ylim=c(0,0.8),pch=19)
lines(rt11$V2,rt11$V4)
points(rt12$V2,rt12$V4,pch=19)
lines(rt12$V2,rt12$V4)
points(rt13$V2,rt13$V4,pch=19)
lines(rt13$V2,rt13$V4)
points(rt21$MinZenith,rt21$GapFraction,pch=21)
lines(rt21$MinZenith,rt21$GapFraction,lty="dashed")
points(rt22$MinZenith,rt22$GapFraction,pch=21)
lines(rt22$MinZenith,rt22$GapFraction,lty="dashed")
points(rt23$MinZenith,rt23$GapFraction,pch=21)
lines(rt23$MinZenith,rt23$GapFraction,lty="dashed")


rt11<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01HM5.TXT")
rt12<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_02HM5.TXT")
rt13<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03HM5.TXT")
rt21<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt22<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_02004_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt23<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03002_Hi0-35_LS80_In5_Record.txt",head=TRUE)
plot(rt11$V2,rt11$V4, ylab="GapFraction",xlab="Zenith",ylim=c(0,0.2),pch=19)
lines(rt11$V2,rt11$V4)
points(rt12$V2,rt12$V4,pch=19)
lines(rt12$V2,rt12$V4)
points(rt13$V2,rt13$V4,pch=19)
lines(rt13$V2,rt13$V4)
points(rt21$MinZenith,rt21$GapFraction,pch=21)
lines(rt21$MinZenith,rt21$GapFraction,lty="dashed")
points(rt22$MinZenith,rt22$GapFraction,pch=21)
lines(rt22$MinZenith,rt22$GapFraction,lty="dashed")
points(rt23$MinZenith,rt23$GapFraction,pch=21)
lines(rt23$MinZenith,rt23$GapFraction,lty="dashed")


rt11<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01HM5.TXT")
rt12<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_02HM5.TXT")
rt13<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03HM5.TXT")
rt21<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt22<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_02004_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt23<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03002_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt31<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt32<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_02004_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt33<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03002_Hi0-35_LS255_In5_Record.txt",head=TRUE)
plot(rt11$V2,(rt11$V4+rt12$V4+rt13$V4)/3, ylab="GapFraction",xlab="Zenith",ylim=c(0,0.06),pch=24)
lines(rt11$V2,(rt11$V4+rt12$V4+rt13$V4)/3)
points(rt21$MinZenith,(rt21$GapFraction+rt22$GapFraction+rt23$GapFraction)/3,pch=21)
lines(rt21$MinZenith,(rt21$GapFraction+rt22$GapFraction+rt23$GapFraction)/3,lty="dashed")
points(rt31$MinZenith,(rt31$GapFraction+rt32$GapFraction+rt33$GapFraction)/3,pch=19)
lines(rt31$MinZenith,(rt31$GapFraction+rt32$GapFraction+rt33$GapFraction)/3,lty="dashed")



rt11<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_9bHM5.TXT")
rt12<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_3bHM5.TXT")
rt13<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_15bHM5.TXT")
rt21<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt22<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0242001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt23<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0341001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt31<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt32<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0242001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt33<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0341001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
plot(rt11$V2,(rt11$V4+rt12$V4+rt13$V4)/3, ylab="GapFraction",xlab="Zenith",ylim=c(0,0.4),pch=24)
lines(rt11$V2,(rt11$V4+rt12$V4+rt13$V4)/3)
points(rt21$MinZenith,(rt21$GapFraction+rt22$GapFraction+rt23$GapFraction)/3,pch=21)
lines(rt21$MinZenith,(rt21$GapFraction+rt22$GapFraction+rt23$GapFraction)/3,lty="dashed")
points(rt31$MinZenith,(rt31$GapFraction+rt32$GapFraction+rt33$GapFraction)/3,pch=19)
lines(rt31$MinZenith,(rt31$GapFraction+rt32$GapFraction+rt33$GapFraction)/3,lty="dashed")

rt11<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_1bHM5.TXT")
rt12<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_2bHM5.TXT")
rt13<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_3bHM5.TXT")
rt21<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_01001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt22<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_02001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt23<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_03001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt31<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_01001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt32<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_02001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt33<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_03001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
plot(rt11$V2,(rt11$V4+rt12$V4+rt13$V4)/3, ylab="GapFraction",xlab="Zenith",ylim=c(0,0.05),pch=24)
lines(rt11$V2,(rt11$V4+rt12$V4+rt13$V4)/3)
points(rt21$MinZenith,(rt21$GapFraction+rt22$GapFraction+rt23$GapFraction)/3,pch=21)
lines(rt21$MinZenith,(rt21$GapFraction+rt22$GapFraction+rt23$GapFraction)/3,lty="dashed")
points(rt31$MinZenith,(rt31$GapFraction+rt32$GapFraction+rt33$GapFraction)/3,pch=19)
lines(rt31$MinZenith,(rt31$GapFraction+rt32$GapFraction+rt33$GapFraction)/3,lty="dashed")



rt11<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_9bHM5Ma81.TXT")
rt12<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_3bHM5Ma81.TXT")
rt13<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_40bHM5Ma81.TXT")
rt21<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt22<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0242001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt23<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0341001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt31<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt32<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0242001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt33<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0341001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
plot(rt11$V2,(rt11$V4+rt12$V4+rt13$V4)/3, ylab="GapFraction",xlab="Zenith",ylim=c(0,0.7),pch=24)
lines(rt11$V2,(rt11$V4+rt12$V4+rt13$V4)/3)
points(rt21$MinZenith,(rt21$GapFraction+rt22$GapFraction+rt23$GapFraction)/3,pch=21)
lines(rt21$MinZenith,(rt21$GapFraction+rt22$GapFraction+rt23$GapFraction)/3,lty="dashed")
points(rt31$MinZenith,(rt31$GapFraction+rt32$GapFraction+rt33$GapFraction)/3,pch=19)
lines(rt31$MinZenith,(rt31$GapFraction+rt32$GapFraction+rt33$GapFraction)/3,lty="dashed")

rt11<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_9bHM5.TXT")
rt12<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_3bHM5.TXT")
rt13<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_40bHM5.TXT")
rt21<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt22<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0242001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt23<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0341001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt31<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt32<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0242001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt33<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0341001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
plot(rt11$V2,(rt11$V4+rt12$V4+rt13$V4)/3, ylab="GapFraction",xlab="Zenith",ylim=c(0,0.7),pch=24)
lines(rt11$V2,(rt11$V4+rt12$V4+rt13$V4)/3)
points(rt21$MinZenith,(rt21$GapFraction+rt22$GapFraction+rt23$GapFraction)/3,pch=21)
lines(rt21$MinZenith,(rt21$GapFraction+rt22$GapFraction+rt23$GapFraction)/3,lty="dashed")
points(rt31$MinZenith,(rt31$GapFraction+rt32$GapFraction+rt33$GapFraction)/3,pch=19)
lines(rt31$MinZenith,(rt31$GapFraction+rt32$GapFraction+rt33$GapFraction)/3,lty="dashed")


rt11<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_1bHM5.TXT")
rt12<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_2bHM5.TXT")
rt13<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_3bHM5.TXT")
rt21<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt22<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_02004_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt23<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03002_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt31<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt32<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_02004_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt33<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03002_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt41<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_010052_Hi0-35_LS80_In5_Record2.txt",head=TRUE)
rt42<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_020042_Hi0-35_LS80_In5_Record2.txt",head=TRUE)
rt43<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_030022_Hi0-35_LS80_In5_Record2.txt",head=TRUE)
plot(rt11$V2,(rt11$V4+rt12$V4+rt13$V4)/3, ylab="GapFraction",xlab="Zenith",ylim=c(0,0.06),pch=24)
lines(rt11$V2,(rt11$V4+rt12$V4+rt13$V4)/3)
points(rt21$MinZenith,(rt21$GapFraction+rt22$GapFraction+rt23$GapFraction)/3,pch=21)
lines(rt21$MinZenith,(rt21$GapFraction+rt22$GapFraction+rt23$GapFraction)/3,lty="dashed")
points(rt31$MinZenith,(rt31$GapFraction+rt32$GapFraction+rt33$GapFraction)/3,pch=19)
lines(rt31$MinZenith,(rt31$GapFraction+rt32$GapFraction+rt33$GapFraction)/3,lty="dashed")
points(rt41$MinZenith,(rt41$GapFraction+rt42$GapFraction+rt43$GapFraction)/3,pch=22)
lines(rt41$MinZenith,(rt41$GapFraction+rt42$GapFraction+rt43$GapFraction)/3,lty="dashed")

rt11<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_1bHM5.TXT")
rt21<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt31<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt41<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_010052_Hi0-999998_LS80_In5_Record.txt",head=TRUE)
plot(rt11$V2,rt11$V4, ylab="GapFraction",xlab="Zenith",ylim=c(0,0.1),pch=24)
lines(rt11$V2,rt11$V4)
points(rt21$MinZenith,rt21$GapFraction,pch=21)
lines(rt21$MinZenith,rt21$GapFraction,lty="dashed")
points(rt31$MinZenith,rt31$GapFraction,pch=19)
lines(rt31$MinZenith,rt31$GapFraction,lty="dashed")
points(rt41$MinZenith,rt41$GapFraction,pch=22)
lines(rt41$MinZenith,rt41$GapFraction,lty="dashed")



rt11<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_1bHM5.TXT")
rt12<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_2bHM5.TXT")
rt13<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_3bHM5.TXT")
rt21<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_01001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt22<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_02001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt23<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_03001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt31<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_01001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt32<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_02001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt33<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_03001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt41<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_010012_Hi0-35_LS80_In5_Record2.txt",head=TRUE)
rt42<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_020012_Hi0-35_LS80_In5_Record2.txt",head=TRUE)
rt43<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_030012_Hi0-35_LS80_In5_Record2.txt",head=TRUE)
plot(rt11$V2,(rt11$V4+rt12$V4+rt13$V4)/3, ylab="GapFraction",xlab="Zenith",ylim=c(0,0.06),pch=24)
lines(rt11$V2,(rt11$V4+rt12$V4+rt13$V4)/3)
points(rt21$MinZenith,(rt21$GapFraction+rt22$GapFraction+rt23$GapFraction)/3,pch=21)
lines(rt21$MinZenith,(rt21$GapFraction+rt22$GapFraction+rt23$GapFraction)/3,lty="dashed")
points(rt31$MinZenith,(rt31$GapFraction+rt32$GapFraction+rt33$GapFraction)/3,pch=19)
lines(rt31$MinZenith,(rt31$GapFraction+rt32$GapFraction+rt33$GapFraction)/3,lty="dashed")
points(rt41$MinZenith,(rt41$GapFraction+rt42$GapFraction+rt43$GapFraction)/3,pch=22)
lines(rt41$MinZenith,(rt41$GapFraction+rt42$GapFraction+rt43$GapFraction)/3,lty="dashed")



rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_3bHM5.TXT")
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_03001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Krz/Krz_03001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
plot(rt1$V2,rt1$V4,type="l",col="red", ylab="GapFraction",xlab="Zenith",ylim=c(0,0.06))
lines(rt1$V2,rt2$GapFraction,type="l",lty="dashed",col="green")
lines(rt1$V2,rt3$GapFraction,type="l",lty="dotted",col="blue")


rt11<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_3bHM5.TXT")
rt12<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_7bHM5.TXT")
rt13<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_9bHM5.TXT")
rt14<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_10bHM5.TXT")
rt15<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_12bHM5.TXT")
rt16<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_14bHM5.TXT")
rt17<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_15bHM5.TXT")
rt18<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_16bHM5.TXT")
rt19<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_40bHM5.TXT")
rt10<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_43bHM5.TXT")
rt21<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt22<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0242001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt23<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0341001_Hi0-35_LS80_In5_Record.txt",head=TRUE)
rt31<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt32<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0242001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt33<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_0341001_Hi0-35_LS255_In5_Record.txt",head=TRUE)
rt41<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_010012_Hi0-35_LS80_In5_Record2.txt",head=TRUE)
rt42<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_02420012_Hi0-35_LS80_In5_Record2.txt",head=TRUE)
rt43<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_03410012_Hi0-35_LS80_In5_Record2.txt",head=TRUE)
plot(rt11$V2,(rt11$V4+rt12$V4+rt13$V4+rt14$V4+rt15$V4+rt16$V4+rt17$V4+rt18$V4+rt19$V4+rt10$V4)/10, ylab="GapFraction",xlab="Zenith",ylim=c(0,0.7),pch=24)
lines(rt11$V2,(rt11$V4+rt12$V4+rt13$V4+rt14$V4+rt15$V4+rt16$V4+rt17$V4+rt18$V4+rt19$V4+rt10$V4)/10)
points(rt21$MinZenith,(rt21$GapFraction+rt22$GapFraction+rt23$GapFraction)/3,pch=21)
lines(rt21$MinZenith,(rt21$GapFraction+rt22$GapFraction+rt23$GapFraction)/3,lty="dashed")
points(rt31$MinZenith,(rt31$GapFraction+rt32$GapFraction+rt33$GapFraction)/3,pch=19)
lines(rt31$MinZenith,(rt31$GapFraction+rt32$GapFraction+rt33$GapFraction)/3,lty="dashed")
points(rt41$MinZenith,(rt41$GapFraction+rt42$GapFraction+rt43$GapFraction)/3,pch=22)
lines(rt41$MinZenith,(rt41$GapFraction+rt42$GapFraction+rt43$GapFraction)/3,lty="dashed")


rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn01005_SB255_0.5In5.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",xlim=c(5,28),ylim=c(0,6),pch=19)
lines((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",lty="dashed")
points((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down)*5,pch=24)
lines((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down)*5)
rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn01005_SB80_0.5In5.txt",head=TRUE)
points((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",xlim=c(5,28),ylim=c(0,6),pch=21)
lines((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",lty="dashed")
points((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down)*5,pch=25)
lines((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down)*5)
axis(4,0:6,c(0:6)/5)

rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn03002_SB255_0.5In5.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",xlim=c(5,28),ylim=c(0,6),pch=19)
lines((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",lty="dashed")
points((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down)*5,pch=24)
lines((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down)*5)
rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn03002_SB80_0.5In5.txt",head=TRUE)
points((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",xlim=c(5,28),ylim=c(0,6),pch=21)
lines((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",lty="dashed")
points((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down)*5,pch=25)
lines((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down)*5)
axis(4,0:6,c(0:6)/5)

rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB01001_SB255_0.5In5.txt",head=TRUE)
plot((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",xlim=c(4,10),ylim=c(0,3),pch=19)
lines((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",lty="dashed")
points((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down),pch=24)
lines((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down))
rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB01001_SB80_0.5In5.txt",head=TRUE)
points((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",xlim=c(4,10),ylim=c(0,3),pch=21)
lines((rt1$down+rt1$up)/2,rt1$Leafangle, ylab="x->G",xlab="Height",lty="dashed")
points((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down),pch=25)
lines((rt1$down+rt1$up)/2,rt1$LAI/(rt1$up-rt1$down))
axis(4)




rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi20-20.5_LS80_In5_Record.txt",head=TRUE)
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi20-20.5_LS255_In5_Record.txt",head=TRUE)
plot(rt1$MinZenith,rt1$GapFraction,type="l",col="red", ylab="GapFraction",xlab="Zenith",ylim=c(0.5,1))
lines(rt2$MinZenith,rt2$GapFraction,type="l",col="green")
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi24.5-25_LS80_In5_Record.txt",head=TRUE)
rt4<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi24.5-25_LS255_In5_Record.txt",head=TRUE)
lines(rt3$MinZenith,rt3$GapFraction,type="l",col="red",lty="dashed")
lines(rt4$MinZenith,rt4$GapFraction,type="l",lty="dashed",col="green")
rt5<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi26.5-27_LS80_In5_Record.txt",head=TRUE)
rt6<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi26.5-27_LS255_In5_Record.txt",head=TRUE)
lines(rt5$MinZenith,rt5$GapFraction,type="l",col="red")
lines(rt6$MinZenith,rt6$GapFraction,type="l",col="green")



rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi20-20.5_LS80_In5_Record.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi24.5-25_LS80_In5_Record.txt",head=TRUE)
rt5<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi26.5-27_LS80_In5_Record.txt",head=TRUE)
rt7<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi18.5-19_LS80_In5_Record.txt",head=TRUE)
plot(rt1$MinZenith,rt1$GapFraction,type="l",col="red", ylab="GapFraction",xlab="Zenith",ylim=c(0,1))
lines(rt2$MinZenith,rt3$GapFraction,type="l",col="green")
lines(rt2$MinZenith,rt5$GapFraction,type="l",col="blue")
lines(rt2$MinZenith,rt7$GapFraction,type="l",col="yellow")

rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi9-10_LS80_In5_Record.txt",head=TRUE)
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi11-12_LS80_In5_Record.txt",head=TRUE)
rt5<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi14-15_LS80_In5_Record.txt",head=TRUE)
rt7<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_01005_Hi17-17.5_LS80_In5_Record.txt",head=TRUE)
plot(rt1$MinZenith,rt1$GapFraction,type="l",col="red", ylab="GapFraction",xlab="Zenith",ylim=c(0,1))
lines(rt2$MinZenith,rt3$GapFraction,type="l",col="green")
lines(rt2$MinZenith,rt5$GapFraction,type="l",col="blue")
lines(rt2$MinZenith,rt7$GapFraction,type="l",col="yellow")



rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03002_Hi20-20.5_LS80_In5_Record.txt",head=TRUE)
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03002_Hi20-20.5_LS255_In5_Record.txt",head=TRUE)
plot(rt1$MinZenith,rt1$GapFraction,type="l",col="green", ylab="GapFraction",xlab="Zenith",ylim=c(0.5,1))
lines(rt2$MinZenith,rt2$GapFraction,type="l",lty="dashed",col="green")
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03002_Hi24.5-25_LS80_In5_Record.txt",head=TRUE)
rt4<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03002_Hi24.5-25_LS255_In5_Record.txt",head=TRUE)
lines(rt3$MinZenith,rt3$GapFraction,type="l",col="red")
lines(rt4$MinZenith,rt4$GapFraction,type="l",lty="dashed",col="red")
rt5<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03002_Hi26-26.5_LS80_In5_Record.txt",head=TRUE)
rt6<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03002_Hi26-26.5_LS255_In5_Record.txt",head=TRUE)
lines(rt5$MinZenith,rt5$GapFraction,type="l",col="blue")
lines(rt6$MinZenith,rt6$GapFraction,type="l",lty="dashed",col="blue")

rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01001_Hi4.5-5_LS80_In5_Record.txt",head=TRUE)
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01001_Hi4.5-5_LS255_In5_Record.txt",head=TRUE)
plot(rt1$MinZenith,rt1$GapFraction,type="l",col="green", ylab="GapFraction",xlab="Zenith",ylim=c(0.5,1))
lines(rt2$MinZenith,rt2$GapFraction,type="l",lty="dashed",col="green")
rt3<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01001_Hi8-8.5_LS80_In5_Record.txt",head=TRUE)
rt4<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01001_Hi8-8.5_LS255_In5_Record.txt",head=TRUE)
lines(rt3$MinZenith,rt3$GapFraction,type="l",col="red")
lines(rt4$MinZenith,rt4$GapFraction,type="l",lty="dashed",col="red")
rt5<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01001_Hi9.5-10_LS80_In5_Record.txt",head=TRUE)
rt6<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/FFB/FFB_01001_Hi9.5-10_LS255_In5_Record.txt",head=TRUE)
lines(rt5$MinZenith,rt5$GapFraction,type="l",col="blue")
lines(rt6$MinZenith,rt6$GapFraction,type="l",lty="dashed",col="blue")



rt1<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03002_Hi24.5-25_LS80_In5_Record.txt",head=TRUE)
rt2<- read.table("E:/Dokumente und Einstellungen/hp/Eigene Dateien/Stn/Stn_03002_Hi24.5-25_LS255_In5_Record.txt",head=TRUE)
rt1$GapFraction
rt2$GapFraction
rt1$GapFraction-rt2$GapFraction
ave((rt1$GapFraction-rt2$GapFraction)^2)



